// Builds the tower-placement mask from the map PNG.
//
// A cell is buildable only if it is predominantly open grass. That single test
// rules out the stone path, the tree canopy, the rock clusters, the hospital
// buildings and the asphalt driveway in one pass, because grass is the only
// large green-dominant, mid-brightness region in the image.
//
// Usage:
//   node scripts/trace-terrain.mjs --emit [--debug /tmp/terrain.png]

import fs from 'node:fs';
import path from 'node:path';
import { PNG } from 'pngjs';

const CELL = 16;
const FILL = 0.72; // fraction of a cell that must be grass for it to be buildable

const SRC = path.resolve('public/assets/map/field.png');
const OUT = path.resolve('src/game/data/terrain.generated.ts');

const png = PNG.sync.read(fs.readFileSync(SRC));
const { width: W, height: H, data } = png;

const isGrass = (i) => {
  const r = data[i * 4], g = data[i * 4 + 1], b = data[i * 4 + 2];
  const bright = (r + g + b) / 3;
  // Green-dominant and not in deep shade. The floor sits below the vignetted
  // grass near the map edges but above the tree canopy, which is both darker
  // and bluer than any lit grass.
  return g - Math.max(r, b) > 16 && bright > 86 && g > 108;
};

const cols = Math.floor(W / CELL);
const rows = Math.floor(H / CELL);
let cells = new Uint8Array(cols * rows);
for (let cy = 0; cy < rows; cy++) {
  for (let cx = 0; cx < cols; cx++) {
    let hit = 0;
    for (let y = cy * CELL; y < (cy + 1) * CELL; y++)
      for (let x = cx * CELL; x < (cx + 1) * CELL; x++) if (isGrass(y * W + x)) hit++;
    cells[cy * cols + cx] = hit / (CELL * CELL) >= FILL ? 1 : 0;
  }
}

// Majority smoothing: flowers, grass tufts and cobble highlights leave single-cell
// speckle that would otherwise read as arbitrary holes in open ground.
const neighbours = (src, cx, cy) => {
  let open = 0, total = 0;
  for (let dy = -1; dy <= 1; dy++)
    for (let dx = -1; dx <= 1; dx++) {
      if (!dx && !dy) continue;
      const nx = cx + dx, ny = cy + dy;
      if (nx < 0 || nx >= cols || ny < 0 || ny >= rows) continue;
      total++;
      if (src[ny * cols + nx]) open++;
    }
  return { open, total };
};
for (let pass = 0; pass < 2; pass++) {
  const next = Uint8Array.from(cells);
  for (let cy = 0; cy < rows; cy++)
    for (let cx = 0; cx < cols; cx++) {
      const { open, total } = neighbours(cells, cx, cy);
      const i = cy * cols + cx;
      if (!cells[i] && open >= total - 2) next[i] = 1;      // fill pinholes
      else if (cells[i] && open <= 2) next[i] = 0;          // drop islands
    }
  cells = next;
}

const grid = [];
for (let cy = 0; cy < rows; cy++) {
  let row = '';
  for (let cx = 0; cx < cols; cx++) row += cells[cy * cols + cx] ? '1' : '0';
  grid.push(row);
}

const buildable = grid.join('').split('').filter((c) => c === '1').length;
console.error(`grid ${cols}x${rows} @${CELL}px — ${buildable}/${cols * rows} cells buildable (${((100 * buildable) / (cols * rows)).toFixed(1)}%)`);

const dbgIdx = process.argv.indexOf('--debug');
if (dbgIdx !== -1) {
  const outPath = process.argv[dbgIdx + 1] ?? '/tmp/terrain.png';
  for (let cy = 0; cy < rows; cy++)
    for (let cx = 0; cx < cols; cx++) {
      if (grid[cy][cx] === '1') continue;
      for (let y = cy * CELL; y < (cy + 1) * CELL; y++)
        for (let x = cx * CELL; x < (cx + 1) * CELL; x++) {
          const i = (y * W + x) * 4;
          data[i] = (data[i] * 0.45) | 0;
          data[i + 1] = (data[i + 1] * 0.45) | 0;
          data[i + 2] = (data[i + 2] * 0.45 + 90) | 0;
        }
    }
  const SW = W >> 1, SH = H >> 1;
  const small = new PNG({ width: SW, height: SH });
  for (let y = 0; y < SH; y++)
    for (let x = 0; x < SW; x++) {
      let r = 0, g = 0, b = 0;
      for (let dy = 0; dy < 2; dy++)
        for (let dx = 0; dx < 2; dx++) {
          const i = ((y * 2 + dy) * W + (x * 2 + dx)) * 4;
          r += data[i]; g += data[i + 1]; b += data[i + 2];
        }
      const o = (y * SW + x) * 4;
      small.data[o] = r >> 2; small.data[o + 1] = g >> 2; small.data[o + 2] = b >> 2; small.data[o + 3] = 255;
    }
  fs.writeFileSync(outPath, PNG.sync.write(small));
  console.error(`wrote ${outPath} (blue tint = blocked)`);
}

if (process.argv.includes('--emit')) {
  const body = grid.map((r) => `  '${r}',`).join('\n');
  fs.writeFileSync(
    OUT,
    `// GENERATED by scripts/trace-terrain.mjs — do not edit by hand.\n` +
      `// Row-major buildability mask over public/assets/map/field.png.\n` +
      `// '1' = open grass a tower may occupy, '0' = path, trees, rocks or buildings.\n\n` +
      `export const TERRAIN_CELL = ${CELL};\n` +
      `export const TERRAIN_COLS = ${cols};\n` +
      `export const TERRAIN_ROWS = ${rows};\n\n` +
      `export const TERRAIN_MASK: readonly string[] = [\n${body}\n];\n`,
    'utf8'
  );
  console.error(`wrote ${path.relative(process.cwd(), OUT)}`);
}
